server:
  port: 3009

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
